Added balances pallet
opentensor/subtensor-Deprecated- pull request #3
Opened 2020-12-10 19:19 UTC by shibshib

This PR adds the balance pallet, which updates balances whenever we add stake, subscribe, or unsubscribe from the neuron.

2020-12-14 16:06 UTC, unconst requested changes

2020-12-14 16:06 UTC, unconst commented on .circleci/config.yml
> +jobs:
this is great, well done

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/Cargo.toml
> +fixed = "1.5"
why is fixed not using the default features?

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
>          TotalStake: u32;
tab error

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +		//CurrentBalance: BalanceOf<T> = T::CurrentBalance::get();
remove this

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			RuntimeLogger::init();
can we switch set_weights and emit. They should be the same function because set _weights should trigger an emit
we need to emit before they set weights or else people can cheat each other

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let total_stake: u32  = TotalStake::get();
This is a lingering issue. But by design we should enforce that the weight sum to the u32 max value. 
This makes the check easy. It is also how we set it in the python code.

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let total_stake: u32  = TotalStake::get();
-- we need to check that weight_sum == u32_max
-- we should need to check that the weight_sum does not overflow the u32_max so this will require that we 
check (u32_max - next_weight) <= current_weight_sum ----> current_weight_sum += next_weight

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			debug::info!("Minimum balance for an account is {:?}", T::Currency::minimum_balance());
What if give them T::Currency::minimum_balance() instead

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let _ = T::Currency::withdraw(&neuron, stake_currency, WithdrawReasons::except(WithdrawReason::Tip), ExistenceRequirement::KeepAlive);
Does this a throw an error if there is no balance to remove?

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let _ = T::Currency::withdraw(&neuron, stake_currency, WithdrawReasons::except(WithdrawReason::Tip), ExistenceRequirement::KeepAlive);
WithdrawReason::Tip what are the other reasons? is this the best?

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let _ = T::Currency::withdraw(&neuron, stake_currency, WithdrawReasons::except(WithdrawReason::Tip), ExistenceRequirement::KeepAlive);
ExistenceRequirement::KeepAlive What is keep alive here?

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let stake_currency = Self::u32_to_balance(stake_amount);
I think we should probably check the removal from balances before we add the stake to the stake account. Not sure what happens if they can't withdraw that amount.

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let new_stake = Self::u32_to_balance(Stake::<T>::get(&new_neuron));
We should add to the current stake balance. Just as a check? what if they already have stake on that key? An other user can add stake to an account right?

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let new_stake = Self::u32_to_balance(Stake::<T>::get(&new_neuron));
if we use Stake::put it will erase the current balance.

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let _ = T::Currency::deposit_into_existing(&new_neuron, Self::u32_to_balance(subscription_gift));
Why are we also depositing to the balance account. This should only occur when the user unsubscribes?

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			let _ = T::Currency::withdraw(&new_neuron, new_stake, WithdrawReasons::except(WithdrawReason::Tip), ExistenceRequirement::KeepAlive);
Is this for testing purposes?

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			// POSSIBLE DIVISION BY ZERO HERE.
This can't be a div by zero since we explicity check that total_stake_u32 > 0
However we need to actualy break if the stake_fraction_u32_f32 is zero and break here. we dont do it.

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			WeightVals::<T>::insert(&calling_neuron, &values);
Big thing here is that we need to do the emission step before we set the weight, otherwise people can cheat by setting weight to someone for a long time and then change them just before they do an emit

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			WeightVals::<T>::insert(&calling_neuron, &values);
Maybe turn emit in to a function you can call first, you should also emit before you unstake for isntance...

2020-12-14 16:06 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +				let _ = T::Currency::withdraw(&calling_neuron, withdraw_amount, WithdrawReasons::except(WithdrawReason::Tip), ExistenceRequirement::KeepAlive);
Why are we withdrawling here? we should only be adding to the stake balance

2020-12-14 16:06 UTC, unconst commented on runtime/src/lib.rs
> +	pub const MaxScheduledPerBlock: u32 = 50;
tab error

2020-12-14 16:06 UTC, unconst commented on runtime/src/lib.rs
> +parameter_types! {
Is this from pulling the latest sustrate code?

2020-12-14 18:34 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			RuntimeLogger::init();
Nothing is calling emit() presently though, do you mean we should switch their call on bittensor side too?

2020-12-14 18:35 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			debug::info!("Minimum balance for an account is {:?}", T::Currency::minimum_balance());
`T::Currency::minimum_balance()` is just a representation of what the minimum balance allowed is, using it to give someone stake is an anti-pattern.

2020-12-14 18:36 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			let _ = T::Currency::withdraw(&neuron, stake_currency, WithdrawReasons::except(WithdrawReason::Tip), ExistenceRequirement::KeepAlive);
withdrawreason::tip is not the reason, it says `except` , meaning use any other reason besides `tip`. 

existencerequirement::keepalive is basically saying if this node's currency goes below the minimum balance, don't remove it from the chain, in hindsight this should be allowdeath

2020-12-14 20:11 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			let _ = T::Currency::deposit_into_existing(&new_neuron, Self::u32_to_balance(subscription_gift));
Everyone starts with 0 stake here, so this is a test fixture so that we can test the kusanagi network with it. We are gifting every subscriber 1000 tokens so they can start off.

2020-12-14 20:11 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			let _ = T::Currency::withdraw(&new_neuron, new_stake, WithdrawReasons::except(WithdrawReason::Tip), ExistenceRequirement::KeepAlive);
Yes. Each time we add to stake, we withdraw from balance.

2020-12-14 20:16 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			// POSSIBLE DIVISION BY ZERO HERE.
This is an old comment, i added the explicit check to make sure we remember. Will take that out.

2020-12-14 20:18 UTC, shibshib commented on pallets/subtensor/Cargo.toml
> +fixed = "1.5"
GOod point, fixed.

2020-12-14 20:19 UTC, shibshib commented on pallets/subtensor/src/lib.rs
>          TotalStake: u32;
Not sure why i'm not seeing this in my vscode? it's weird.

2020-12-14 20:19 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +		//CurrentBalance: BalanceOf<T> = T::CurrentBalance::get();
Done.

2020-12-14 20:20 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			let stake_currency = Self::u32_to_balance(stake_amount);
Good point, added check

2020-12-14 20:48 UTC, shibshib commented on runtime/src/lib.rs
> +	pub const MaxScheduledPerBlock: u32 = 50;
again, i think it's a git thing, it's not tabbed on my vscode

2020-12-14 20:49 UTC, shibshib commented on runtime/src/lib.rs
> +parameter_types! {
I believe so, yes.

2020-12-14 20:53 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +				let _ = T::Currency::withdraw(&calling_neuron, withdraw_amount, WithdrawReasons::except(WithdrawReason::Tip), ExistenceRequirement::KeepAlive);
Good point, removed.

2020-12-15 00:48 UTC, unconst commented on pallets/subtensor/src/lib.rs
> +			// POSSIBLE DIVISION BY ZERO HERE.
Awesome

2020-12-15 18:39 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			WeightVals::<T>::insert(&calling_neuron, &values);
Separated the functions. Will do the change on Bittensor side to call emit then set weights. The issue with calling set_weights within emit in Rust is that when you emit an event it's moved out of the context, so it just creates weird code. I think it's cleaner to re-separate them again.

2020-12-15 18:40 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			RuntimeLogger::init();
Separated the functions so that we can call emit before setting the weights.

2020-12-15 20:53 UTC, shibshib commented on pallets/subtensor/src/lib.rs
> +			let total_stake: u32  = TotalStake::get();
Good point, made a check in the weight summation for normalization: we make a check, if `u32_max - x_u32_f32 <= w_sum` then we add to the next weight to the current weight sum.

2020-12-15 22:34 UTC, unconst approved these changes

2020-12-15 22:34 UTC, unconst commented on pallets/subtensor/src/lib.rs
>          TotalStake: u32;
still untabbed

2020-12-15 22:34 UTC, merged